# jdk 21
FROM maven:3.9.4-eclipse-temurin-21 AS build
WORKDIR /build

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy source code and build the application
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM amazoncorretto:21
ARG PROFILE=dev
ARG APP_VERSION=1.0.0

WORKDIR /app

# Copy the built JAR from the build stage
COPY --from=build /build/target/Rent-A-Ride-API-${APP_VERSION}.jar /app/

# Expose the application port
EXPOSE 8080

# Environment variables
ENV APP_VERSION=${APP_VERSION}
ENV APP_PROFILE=${PROFILE}
ENV DB_URL=jdbc:postgresql://postgres-sql-rar:5432/vehicle_sharing

# Use shell-style CMD for variable substitution
CMD java -jar -Dspring.profiles.active=${APP_PROFILE} -Dspring.datasource.url=${DB_URL} Rent-A-Ride-API-${APP_VERSION}.jar
