/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BorrowedVehicleResponse } from './models/borrowed-vehicle-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { PageResponseBorrowedVehicleResponse } from './models/page-response-borrowed-vehicle-response';
export type { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export type { PageResponseVehicleResponse } from './models/page-response-vehicle-response';
export type { RegisterationRequest } from './models/registeration-request';
export type { VehicleRequest } from './models/vehicle-request';
export type { VehicleResponse } from './models/vehicle-response';
