services:
  postgres:
    container_name: postgres-sql-rar
    image: postgres
    environment:
      POSTGRES_USER: bala
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: vehicle_sharing
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-rar
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  rar-api:
    container_name: rar-api
    image: rar/rar:1.0.0
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres


networks:
  spring-demo:
    driver: bridge
volumes:
  postgres:
    driver: local

